[tool.poetry]
name = "olivapp"
version = "0.0.3"
description = "Gestor de dependencias para OlivApp project"
authors = ["José Antonio <joseantonio2001>"]
license = "GPL-3.0 license"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.16.4"

[tool.poe.tasks]
installPoetry = "poetry install"
check = "python3.8 -m compileall olivapp/"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
